### ISSUE TITLE
Profile picture 4.3MB file upload fails with a 502 Bad Gateway

### ISSUE THREAD

**Issue by thibaudcolas** [pretalx/pretalx#1709] opened 2024-03-08 05:06 UTC
### Problem and impact

Uploading a profile picture file of 4.3MB is triggering a 502 with nginx.

### Expected behaviour

The image is 4.3MB, 5568 × 3712, so quite large but well below the size limit listed on the form ("Please do not upload files larger than 10.0MB!").

I have resized the image on my computer and was able to upload it.

### Steps to reproduce

1. Go to <https://pretalx.evolutio.pt/orga/event/djangocon-europe-2024/speakers/GPMBWF/>
2. Un-zip and upload [DSC_6306.JPG.zip](https://github.com/pretalx/pretalx/files/14533396/DSC_6306.JPG.zip) (zipped just because I don’t want GitHub to do any image processing).
3. Click "Save"
4. See the 502

### Screenshots

![502 pretalx](https://github.com/pretalx/pretalx/assets/877585/4c0f9fec-7b56-4958-b3e9-859692b08f18)

### Link

https://pretalx.evolutio.pt/orga/event/djangocon-europe-2024/speakers/GPMBWF/

### Browser (software, desktop or mobile?) and version

Chrome 124.0.6342.2 (Official Build) canary (x86_64)

**Comment by rixx** [comment] 2024-03-08 15:25
Hard to say what's going on, given that that's a self-hosted instance and it's hard to say for sure without logs. However, it's probably a duplicate of #1540, which would be resolved with #1285 – sadly, image processing is just a hard problem, and we can't afford to *not* do it, as stripping metadata (at the very least) is a must for online platforms.

**Closed by rixx** 2024-03-08 15:25 UTC
Labels: type: bug

**Comment by thibaudcolas** [comment] 2024-03-08 15:37
thanks 👍 I didn’t consider that instance might be self-hosted.
