### ISSUE TITLE
Profile image upload can trigger 413 "request entity too big" from OpenResty

### ISSUE THREAD

**Issue by candeira** [pretalx/pretalx#1120] opened 2021-06-11 06:27 UTC
## Current Behavior

One of the PyCon AU submitters tried to upload their photo, and they saw an OpenResty error:

<img width="896" alt="413_request_entity_too_large" src="https://user-images.githubusercontent.com/91694/121640760-ac24ca80-cad1-11eb-84c1-ba027031020d.png">

## Expected Behavior

Perhaps some kind of warning about maximum size, so users can figure out how big an image they can upload.

## Context

This is FYI, and is not blocking us.

**Comment by rixx** [comment] 2021-06-11 07:35
Thank you for the report! I'll close this as a duplicate of #1084 – but I'm very thankful for the report. We got a PR with a fix for most image fields, but since the profile picture is special (with the optional gravatar toggle), that one didn't get fixed. Won't be too hard to add though, stay tuned :)

**Closed by rixx** 2021-06-11 07:35 UTC
