### ISSUE TITLE
Required question variant "Choose multiple from a list" don't provide feedback when left empty

### ISSUE THREAD

**Issue by orlando** [pretalx/pretalx#815] opened 2019-11-21 00:15 UTC
## Current Behavior
Required question variant "Choose multiple from a list" don't provide feedback when left empty

## Expected Behavior
It should tell the user that the question requires an answer
## Steps to Reproduce

1. Create a "Choose multiple from a list" question with options and make it required
2. Leave the question empty and try to go to next step
3. Questions page will be rendered again without any feedback

## Context

Creating a required "Choose multiple from a list" question

## Your Environment

* Version used: 1.0.4
* Environment name and version (e.g. Chrome 39, python 3.5): Chrome and Firefox / Python 3.7
* Operating System and version (desktop or mobile): Desktop macOS
* Link to your instance, if in production:

**Comment by rixx** [comment] 2019-11-21 01:24
I can't reproduce this issue under Chromium in current pretalx, which gives me the expected hint. Firefox seems to position it at the very top or bottom of the browser window, which doesn't help anybody.

I haven't found any way to influence Firefox here, though, and since this is an unspec'd browser specific behaviour, I'm going to close this issue. If anybody comes up with a Firefox fix, I'll happily include it in pretalx, though!
![DeepinScreenshot_select-area_20191121021825](https://user-images.githubusercontent.com/2657547/69292319-17fcc500-0c06-11ea-8b60-15cb5cda072d.png)

**Closed by rixx** 2019-11-21 01:24 UTC

**Comment by rixx** [comment] 2019-11-21 19:13
I believe you, but even if I could reproduce it – these validation message bubbles are notoriously browser-dependent and hard to influence in any way.

**Comment by orlando** [comment] 2019-11-21 19:36
@rixx cool here a video anyway. In our case, nothing is preventing the user to submit the form.

https://www.loom.com/share/e8cc866b552d4a67a94a6059a39614ce
