### ISSUE TITLE
Error when installing during 'rebuild' command

### ISSUE THREAD

**Issue by yancho** [pretalx/pretalx#1714] opened 2024-03-13 13:55 UTC
### Problem and impact

When trying to install on a Turnkey Node.js linux, I am getting the below. I am using the `python -m pretalx rebuild`:

`Compressing... Invalid template django_filters/rest_framework/crispy_form.html: 'crispy_forms_tags' is not a registered tag library. Must be one of:
bootstrap4
cache
compress
copyable
filesize
formset_tags
html_signal
humanize
i18n
jquery_tags
l10n
orga_edit_link
rest_framework
review_score
rich_text
rules
static
times
tz
url_replace
vite
xmlescape
Invalid template common/table.html: Invalid block tag on line 10: 'url_replace', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
done
Compressed 41 block(s) from 418 template(s) for 1 context(s).
`

### Expected behaviour

I also tried `pip install django-crispy-forms` but to no avail

### Steps to reproduce

1. Following the tutorial step by step.
2. After migrate, I run rebuild

**Comment by rixx** [comment] 2024-03-13 14:13
Confusingly, that's not an error, just a warning we can't do anything about.

In the future, please search for similar problems before opening an issue: this is a duplicate of #1393.

**Closed by rixx** 2024-03-13 14:13 UTC
Labels: type: bug
