### ISSUE TITLE
Additional Speaker - status of invitation is not shown

### ISSUE THREAD

**Issue by zmiklank** [pretalx/pretalx#1703] opened 2024-02-28 16:11 UTC
### Problem and impact

After submitting a proposal with an additional speaker, it is no longer possible to verify whether the invitation to the additional speaker has been sent or if they have been added to the submission at all until they approve the invitation.

### Expected behaviour

It would be helpful to have some information displayed about the status of inviting additional speakers.
Something like:
"Invitation of speaker NAME SURNAME is waiting for their approval."

### Steps to reproduce

1. Add an additional speaker to the proposal submission.
3. Submit it.
4. View the submitted proposal.

No info about additional speaker is displayed.

### Link

https://pretalx.com/devconf-cz-2024/

**Comment by TomasTomecek** [comment] 2024-02-28 16:17
We have worked with @zmiklank and tried to understand what went wrong. pretalx didn't show any cospeaker even though they were invited. It took us some time to understand what went wrong and find those cospeakers and make them accept the invitations. The status update of the invitation would make this so much easier for us.

**Comment by rixx** [comment] 2024-02-28 19:17
Invites are currently not tracked, so pretalx doesn't have the information you're looking for. Closing as a duplicate of #1302

**Closed by rixx** 2024-02-28 19:17 UTC
Labels: type: bug
