### ISSUE TITLE
Limit tracks/rooms in schedule editor

### ISSUE THREAD

**Issue by johanvdw** [pretalx/pretalx#1025] opened 2020-11-01 21:38 UTC
## Problem you are facing

For a large event with many rooms and tracks, the schedule editor becomes quite hard to use.
![image](https://user-images.githubusercontent.com/868434/97815764-bdcb0780-1c90-11eb-977f-f96aa88848f3.png)

## Possible Solution
* Add an option to show only a specific room (or specific rooms).
* Add an option to filter on track in the unassigned talks.

Ideally, it would even be better if it was possible to create a track responsible 'role' who can only change the scheduling for his specific track, but I see that that entails a lot more work.

## Context
I'm researching alternative options for scheduling FOSDEM, currently (and probably for 2021 as well) we use pentabarf. 
If some guidance is given, I might be able to help developing this.

**Comment by rixx** [comment] 2020-11-02 09:42
Closing as duplicate of #943.

Regardless, your offer of assistance is appreciated! We have a [development setup](contributing.html#commit-messages) guide, and then you'd want to look at the vue.js file that powers the schedule editor, at [pretalx/static/orga/js/schedule.js](https://github.com/pretalx/pretalx/blob/master/src/pretalx/static/orga/js/schedule.js).

The relevant line is L450, `<room v-for="room in rooms" :room="room" :talks="talks" :duration="duration" :start="start" :end="end" :key="room.id">`. Instead of iterating over all rooms, you'd have to iterate over something like `visibleRooms`. `visibleRooms` would be a `computed` property returning all rooms that should be shown. Rooms would then have a `hidden` attribute that could be added or removed with a click, I think. Let me know if you need any further assistance!

**Closed by rixx** 2020-11-02 09:42 UTC
