### ISSUE TITLE
make room labels sticky to top

### ISSUE THREAD

**Issue by flowolf** [pretalx/pretalx#602] opened 2019-03-01 11:14 UTC
## Problem you are facing

when planning an event that is going for more than one day, room labels are removed from view, when editing the schedule for later events. All rooms look the same and are indistinguishable from each other
## Possible Solution

make room labels stick to the top, if they would scroll out of sight.

## Context

I'm trying to set events into rooms, and cannot see which of the 20+ rooms I'm dragging the event to.

**Comment by rixx** [comment] 2019-03-01 11:23
Good point – this is a duplicate of #486.

**Closed by rixx** 2019-03-01 11:23 UTC

**Comment by rixx** [comment] 2019-03-10 18:07
You'll be happy to hear that the issue is fixed!
