### ISSUE TITLE
Display problem on radio input during review

### ISSUE THREAD

**Issue by ewjoachim** [pretalx/pretalx#895] opened 2020-03-08 14:48 UTC
## Current Behavior

When looking at a review I've already made, it looks like this:
<img width="209" alt="Capture d’écran 2020-03-08 à 15 36 45" src="https://user-images.githubusercontent.com/1457576/76164974-72894500-6153-11ea-8f00-2481ee0cd251.png">

## Expected Behavior

It should probably look more like that, which is what I have before I review:
<img width="344" alt="Capture d’écran 2020-03-08 à 15 45 50" src="https://user-images.githubusercontent.com/1457576/76165035-f17e7d80-6153-11ea-9bae-f060eee2c4e4.png">

## Steps to Reproduce

review a submission, stay on the page, look at my review

## Context

It might be linked to #696, or maybe not.

## Your Environment

* Version used: (DjangoCon Europe Porto CFP, I can ask them if you want)
* Environment name and version (e.g. Chrome 39, python 3.5): Firefox 73.0.1
* Operating System and version (desktop or mobile): Mac OS 10.15.3
* Link to your instance, if in production: https://cfp.2020.djangocon.eu

**Comment by evildmp** [comment] 2020-03-08 15:04
I see the same in Safari, on the same instance.

**Comment by rixx** [comment] 2020-03-08 15:23
This must either have been resolved in the meantime, or an instance-specific issue. I can't reproduce it on pretalx.com or locally:
![DeepinScreenshot_select-area_20200308162240](https://user-images.githubusercontent.com/2657547/76165675-24774000-6159-11ea-9c4e-0772646a170c.png)

**Comment by ewjoachim** [comment] 2020-03-08 15:48
This looks like the screenshot you've show is before you review. The problem appears **after** the review:

Before:
<img width="1056" alt="Capture d’écran 2020-03-08 à 16 47 37" src="https://user-images.githubusercontent.com/1457576/76166139-91400980-615c-11ea-916c-ee8bc79bf7e4.png">

After:
<img width="1153" alt="Capture d’écran 2020-03-08 à 16 47 47" src="https://user-images.githubusercontent.com/1457576/76166142-9604bd80-615c-11ea-8e06-f0e34aa05f34.png">

**Comment by rixx** [comment] 2020-03-08 16:07
Ah, apologies, should've read more carefully.

**Closed** 2020-03-08 16:07 UTC
