### ISSUE TITLE
Allow speaker name in email templates

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#654] opened 2019-04-11 11:28 UTC
## Problem you are facing

If I read https://github.com/pretalx/pretalx/blob/78d9fcb634fd72fe13ff4d808daaf511ba13f13a/src/pretalx/mail/context.py correctly, then there's currently no way to start emails with "Dear {speaker_name}". It would be great if you could send personlised emails to people.

## Possible Solution

Add the speaker name to the context. Though I can see that this might be tricky as the emails are submission based.

## Context

I'd like to be more personal and sound less auto-generated.

**Comment by rixx** [comment] 2019-04-21 15:25
Duplicate of #412

**Closed by rixx** 2019-04-21 15:25 UTC
