### ISSUE TITLE
Allow organisers to freeze session data after a certain deadline

### ISSUE THREAD

**Issue by badbadc0ffee** [pretalx/pretalx#1894] opened 2024-11-20 12:48 UTC
### Problem and impact

It would be nice to be able to freeze some data after certain deadlines while other fiels should remain editable.

### Proposed solution / feature

It should be possible to block changes to session data such as abstract, details, notes, in particular additional speakers after a date that should be configurable for each data field separately. The mechanism should be the same that is already available for custom questions.

### Context or examples

Adding speakers should only be allowed before the review phase, it should still be possible to edit notes and add resource links and files until very short before the event.

**Comment by rixx** [comment] 2024-11-27 12:55
Duplicate of #1346

**Closed by rixx** 2024-11-27 12:55 UTC
Labels: type: feature
