### ISSUE TITLE
Firefox "Print" Button

### ISSUE THREAD

**Issue by mailonator** [pretalx/pretalx#625] opened 2019-03-08 16:50 UTC
## Current Behavior
When using The "Print" button of firefox (65.0.2) only the first page is selected and printed.

## Expected Behavior
All pages printed

## Steps to Reproduce
Goto https://fahrplan.das-sendezentrum.de/subscribe10/schedule/ and "Print". 
The preview shows only one page.

## Context

Vivaldi prints all  pages.

## Your Environment

* Version used: 
* Environment name and version (e.g. Chrome 39, python 3.5): firefox 65.0.2-1
* Operating System and version (desktop or mobile): Fedora 29
* Link to your instance, if in production:

**Comment by rixx** [comment] 2019-03-08 22:00
I'm normally developing for Firefox first, but this issue concerns **only** Firefox, no other browsers, and is definietely a Firefox bug. As Firefox got rid of their print.css debugging tooling, and apparently has [no real intention](https://bugzilla.mozilla.org/show_bug.cgi?id=1202711) of bringing it back, I'm afraid this is a wontfix. I just don't have the time and resources to try and find workarounds for bugs in other people's software who are clearly not interested in any fixes.

Sorry – I tried to find a fix for this issue a while back, but without any debugging possibilities it's just guessing in the dark. I'll happily merge a fix for this though, of course, if anybody comes across one!

**Comment by mailonator** [comment] 2019-03-09 20:17
Thanks for the explanation. I guess ... case closed.

**Comment by rixx** [comment] 2019-03-10 11:10
So apparently the issue is that we position talk elements in the schedule via a `top: ...px` offset from the top of that day. But Firefox, in print mode, calculates this offset from the top of the page, so that you'll always only get one page per day of output, and then as many empty pages as there should be filled pages. This is stupid and nothing we can trivially work around.

I'd take to recommending printing with Chromium or Vivaldi or any other browser that works. I've added the fix that allows display of one page per day in Firefox, but it's still pretty unusable due to weird page breaks and empty pages.

**Closed** 2019-03-10 11:12 UTC
Labels: stage:wontfix
