### ISSUE TITLE
Download only the Starred Appointments

### ISSUE THREAD

**Issue by F4zination** [pretalx/pretalx#1780] opened 2024-06-03 09:00 UTC
### Problem and impact

When browsing a packed schedule, I wanted to download only my starred meetings. Unfortunately, this was not possible.

### Proposed solution / feature

Ideally, you should be able to choose to download only the meetings that you have starred.

**Comment by rixx** [comment] 2024-06-05 21:17
Duplicate of #1002. Please search for duplicates before opening new issues.

**Closed by rixx** 2024-06-05 21:17 UTC
Labels: type: feature
