### ISSUE TITLE
Fontawesome-webfont is not found

### ISSUE THREAD

**Issue by rahmonov** [pretalx/pretalx#272] opened 2017-11-16 19:51 UTC
I ran the project for the first time and the console says that the fontawesome is not found. 

## Expected Behavior

It should be found

## Current Behavior

It is not found

## Possible Solution

Remove the versions from static files in /static/vendored/fontawesome/scss/_path.scss 

## Steps to Reproduce (for bugs)

1. Git clone the project
2. Migrate
3. Run
4. You will see that icons are not displayed

## Your Environment

* Version used: latest
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 61
* Operating System and version (desktop or mobile): Mac

**Comment by luto** [comment] 2017-11-16 20:29
Sorry about that! This was probably caused by https://github.com/pretalx/pretalx/commit/c8284298c5e81a00ef2cbcaa1ee2b970d45876b3 (4 hours ago) and was fixed by  https://github.com/pretalx/pretalx/commit/0d36211a52c1f42d26908a9619ffccdf0f3ee698 (20 mins ago). At least a fresh clone on linux works for me.

Can you please update to the latest version, try again and report back? thank you!

**Comment by rahmonov** [comment] 2017-11-17 06:37
@luto yes, it works now. Thank you!

**Closed** 2017-11-17 07:48 UTC
