### ISSUE TITLE
Changing Language of Submission page deletes entered data

### ISSUE THREAD

**Issue by koebi** [pretalx/pretalx#462] opened 2018-07-24 12:59 UTC
## Expected Behavior
I'd like the data I already entered to be still entered after changing the language of the submission page.

## Current Behavior
The entered data gets deleted on changing the language of the submission page.

## Steps to Reproduce

1. Goto https://talks.mrmcd.net/2018/submit/
2. Enter some data
3. click the "german"-button
4. write everything again

## Context

I wanted to submit a talk to MRMCD 18 and now have to retype everything.

**Comment by rixx** [comment] 2018-07-24 20:05
Hmm, a reload of the page will unsubmitted form data – not sure what we can do about that.

**Comment by rixx** [comment] 2018-07-26 20:19
The only way to address this would be storing everything that was typed with JavaScript, and while that may be useful, as we're taking care to not rely on JavaScript overly much, this won't be prioritised.

**Comment by rixx** [comment] 2019-05-01 12:05
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

Some events run in multiple languages, and provide a language switcher in the public interface. As this is just a link, existing form data will disappear when it is clicked, which (as you can see above) is jarring to submitters.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).


## How to do this

The only real way to do this is a JavaScript based solution. It should save form input to LocalStorage and try to retrieve it on page load (async, non-blocking, though!). It should take the event and current submission slug into account.

UI-wise, An indicator that the currently written input is being saved would be good. On page load, restoring past input should be offered (regardless of the current slug, so if multiple sets of input are available, all should be offered). When the submission has been finalized, this data should be removed to avoid offering up submission content that has already been saved.

You'll want to put this script in `pretalx/static/cfp/js/submission_form.js`, and include it in the base view for the submission workflow at `pretalx/cfp/templates/cfp/event/submission_base.html`.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by rixx** [comment] 2023-06-04 16:03
Duplicate of #1107

**Closed by rixx** 2023-06-04 16:03 UTC
Labels: size: regular, type: feature, stage: up for grabs, help wanted, good first issue
