### ISSUE TITLE
Apparent time zone handling issue for speaker availability time ranges

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [pretalx/pretalx#1469] opened 2023-04-23 15:16 UTC
### Problem and impact

Whenever I "save" my availability slots / time ranges, any ranges not covering entire days are shifted forwards by 1h. Since my time zone is Europe/Berlin, it may be using the non-DST offset of that time zone (+1h) incorrectly, which would explain the exact time offset applied.

### Steps to reproduce

1. Edit (your own) speaker profile
2. Be in Europe/Berlin time zone (should be displayed at "Availability"
3. Enter a time range that does neither start nor end at 00:00.
4. Save availability data.
5. Observe the time range to be shifted incorrectly.

### Screenshots

![image](https://user-images.githubusercontent.com/28656157/233848115-5db82015-46e4-4a6c-a92f-defa475a9f05.png)

Only the "15:00-16:00" range has been newly inserted.

Clicking "Save"...

![image](https://user-images.githubusercontent.com/28656157/233848145-667aca4b-50fe-4067-975e-d2c0d1cd1a26.png)

### Browser (software, desktop or mobile?) and version

Chrome 112.0.5615.138 (Windows 10 x86_64)

**Comment by martey** [comment] 2023-04-23 21:23
This looks like it might be a duplicate of #1421. What version of Pretalx are you using?

**Comment by rixx** [comment] 2023-04-24 11:12
Duplicate

**Closed by rixx** 2023-04-24 11:12 UTC
Labels: type: bug
