### ISSUE TITLE
Ability to include reviews in acceptance/rejection email

### ISSUE THREAD

**Issue by oxinabox** [pretalx/pretalx#922] opened 2020-05-09 14:58 UTC
## Problem you are facing
Speakers have made submissions.
The organizers have made a decision as to what to accept.
The reviews have important feedback for the submitters.

There is no way to tell the submitters this information on mass.

## Possible Solution
Add a template element that can be used in the acceptance and rejection emails that will insert the reviews and scores, but not the reviewers names (double blind).

## Context

As a work-around I discarded all acceptance emails generted automatically,
and wrote a script that pulled down everything from the API
and built my own emails that included it.

However, this is a really hacky approach.

**Comment by rixx** [comment] 2020-05-09 17:13
This should absolutely be a feature, thank you for suggesting it! I'll close this issue as a duplicate of #800, and I'm definitely happy to coach anybody who wants to tackle this issue.

**Closed by rixx** 2020-05-09 17:13 UTC
