### ISSUE TITLE
Meaningfull error when viewing own submissions reviews

### ISSUE THREAD

**Issue by momorientes** [pretalx/pretalx#469] opened 2018-08-01 14:26 UTC
## Problem you are facing
As of now reviewers clicking on thei own submission are faced with a 404 wenn checking their own reviews. This feels like a bug eventough it is a great feature!

## Possible Solution
Show an actual error instead of a 404

## Context
Our conference has a program committe with quite a few active speakers in it who were confused with the 404 page

**Comment by rixx** [comment] 2018-08-01 18:04
This is a duplicate of #463, which has already been resolved.

**Closed by rixx** 2018-08-01 18:04 UTC
