### ISSUE TITLE
Links to exports in static schedule export are 404

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#491] opened 2018-09-04 22:38 UTC
## Expected Behavior
The links should 200 in the static export.

## Current Behavior
Links to `.ics`, `.xml`, `.xcal` and `.json` files are 404 since they link to the dynamically generated schedule but under the hostname of the static site.

## Steps to Reproduce

1. Have a schedule that is generated and serve that schedule via a separate HTTP/S host
2. Klick on one of the static links to the export formats mentioned above.
3. 404

Examples:
Static schedule: `https://fahrplan.privacyweek.at/pw18/schedule/`
Linked `.ics`: `https://fahrplan.privacyweek.at/pw18/schedule/export?exporter=core-iCal`

Working Workaround URL: `https://fahrplan.privacyweek.at/pw18/schedule.ics`
This can be used to create rewrites in your webserver.

## Context

Static export is used by a bunch of Apps and Infobeamer. These either must be patched, or manually configured since their autodetection assumptions fail. Or they require configuration of rewrite rules on the server side to deliver them the right content.

## Your Environment

* Version used: 0.7.1 (unless @luto has monkey patched stuff behind my back)
* Environment name and version: Browser independent, Python 3.6 on the server
* Operating System and version (desktop or mobile): macOS Laptop, Arch Linux Laptop
* Link to your instance, if in production: https://cfp.privacyweek.at/ and https://fahrplan.privacyweek.at/pw18/schedule/

**Comment by luto** [comment] 2018-09-04 23:44
depends on https://github.com/pretalx/pretalx/issues/383.

**Comment by rixx** [comment] 2018-09-05 19:05
duplicate of #383, in fact.

**Closed by rixx** 2018-09-05 19:05 UTC
Labels: issue:bug, stage:up for grabs
