### ISSUE TITLE
10-minute talks overlap in the schedule

### ISSUE THREAD

**Issue by blinry** [pretalx/pretalx#932] opened 2020-05-22 19:01 UTC
## Problem you are facing

When building a schedule from talks that are 10 minutes long each, and which are back-to-back, they overlap in the schedule, and highlighting them covers parts of neighboring talks.

![image](https://user-images.githubusercontent.com/81277/82700719-0eb0eb80-9c6f-11ea-9bbf-f7ff6f2aee19.png)

## Possible Solution

Extend the schedule rendering so that 10-minute talks can be represented without overflowing their box.

## Context

Heh, I feel like we're doing many weird things at EnthusiastiCon. :P Hope my feature requests help pretalx be a more generic tool.

**Comment by rixx** [comment] 2020-05-29 08:07
This is pretty hard to figure out, sadly. If we extend talk display, the view of a proportional schedule with very long events is pretty much unusable, because you have to scroll everywhere.

For conferences like this, often the list schedule display is better suited, because it doesn't even try to approach times in a proportional way. Do you think that in itself could be a sufficient solution?

I realise the list schedule display could seem a bit bare-bones, and I'm super happy to add more fanciness to it if you have some feedback about it. Similarly, it's currently not available as a widget, but adding it to that would not be too much of an effort, and I'd be happy to do so, if that would help.

**Comment by oxinabox** [comment] 2020-06-08 22:26
Duplicate of https://github.com/pretalx/pretalx/issues/736

**Comment by rixx** [comment] 2020-06-08 23:30
No, this is not a duplicate – #736 is concerned with the schedule *editor*, whereas this issue is concerned with the attendee facing *schedule*.

**Comment by oxinabox** [comment] 2020-06-09 00:02
Ah yes, we also has this problem last JuliaCon.

It's not quite as bad as #735 as you get to see the whole top line of  the title. Rather than just a few pixels. But it effects a lot more people since it is for attendees rather than for organisers.

**Comment by ViralBShah** [comment] 2020-07-01 18:01
For titles that overflow, it would be nice to have `...` at the end. That would make it much easier to read (at least for me).

**Closed** 2020-09-02 20:48 UTC
