### ISSUE TITLE
Track required, but unpopulated

### ISSUE THREAD

**Issue by jberkus** [pretalx/pretalx#884] opened 2020-02-20 19:41 UTC
## Current Behavior

In one of my events, "Track" is marked as required in CfP::Content.  Yet two submitters were able to submit a proposal with no track.

## Expected Behavior

If Track is required, it should not be possible to submit a proposal without a track selection.

## Steps to Reproduce

At this point, I'm not sure.  I'm wondering if they somehow circumvented it by saving a draft?  Once I get done picking talks for this event, I'll go back and try to reproduce the problem.

## Your Environment

Pretalx hosted.

**Comment by rixx** [comment] 2020-02-25 20:37
This will be a hard one to tackle without any minimal/reproducable setup – any help in finding the issue would be appreciated.

**Comment by rixx** [comment] 2020-06-14 21:34
I'm closing this issue for now, since I have not been able to replicate it – I'm more than happy to re-open it once we have any idea how to replicate it / if the problem still exists.

**Closed by rixx** 2020-06-14 21:34 UTC
Labels: issue:bug 🐛, stage:blocked 🚧

**Comment by jberkus** [comment] 2020-06-16 23:33
That's fine.  I never figured out how they did it.
