### ISSUE TITLE
Reviews: showing links without permission to access them

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#597] opened 2019-02-24 20:16 UTC
## Current Behavior

On the reviews page of an event (/orga/event/<event>/reviews/) there's links to all the submitted talks. You can click on the title to review the talk. The link point to /orga/event/foss4g/submissions/<talkid>/reviews/. You get a "404 Not Found" if you don't have permission to review talks.

## Expected Behavior

Hard to tell, this needs an holistic view on the whole workflow.

Possible behaviours I could think of:
 - Don't make the title a link
 - Don't show the list of talks at all and show a message saying that you don't have permission to review talks.

## Steps to Reproduce

1. Create a conference
2. Submit a talk
3. Sign in with an admin account that doesn't have permission to review talks
3. Go to /orga/event/<event>/reviews/

## Context

It was just confusing me and I thought I'm hitting a bug where the URLs were wrong (because of the 404). It took me a bit to realise that it was a permission issue.

## Your Environment

* Version used: HEAD (64608a8521d8945f8fad1ed0958271ad6cf040be)
* Environment name and version (e.g. Chrome 39, python 3.5): Firefox
* Operating System and version (desktop or mobile): Linux, desktop

**Comment by rixx** [comment] 2019-02-24 20:43
You are correct, but we already have a tracking issue: This is a duplicate of #433.

**Closed by rixx** 2019-02-24 20:43 UTC

**Comment by vmx** [comment] 2019-02-24 21:06
Sorry, I should've checked.

**Comment by rixx** [comment] 2019-02-24 21:11
No worries, hearing about more issues with this would normally just help to prioritize it in my development plan, so I'm thankful for any feedback. (This issue is already near the top, though, so I'll get around to it shortly.)
