### ISSUE TITLE
Proposal Export fails in Safari

### ISSUE THREAD

**Issue by logankilpatrick** [pretalx/pretalx#1335] opened 2022-07-21 02:53 UTC
## Current Behavior
I click export and nothing happens

## Expected Behavior
I get a CSV when I click export

## Steps to Reproduce

See the video below:
https://user-images.githubusercontent.com/35577566/180119861-292f179a-bf93-4842-9fc2-3a2923cf5b06.mov

## Your Environment

* Version used: N/A
* Environment name and version (e.g. Chrome 39, python 3.5): MacOS  Safari Version 15.3 (17612.4.9.1.8)
* Operating System and version (desktop or mobile): Desktop

**Comment by logankilpatrick** [comment] 2022-07-21 02:54
CC @nassarhuda I was trying to do this for you but it is currently not working. Stay tuned!

**Comment by rixx** [comment] 2022-07-21 07:00
Thank you for your bug report! So I've just tried to replicate the bug in a non-Safari browser, and the export works as intended.

I'm not super familiar with download handling by Safari – have you checked that there is no `juliacon-2022_sessions.csv` in your downloads directory?

If not, then I'm honestly stumped, especially because your browser clearly loads the requested file and URL, and doesn't show any errors …

**Comment by logankilpatrick** [comment] 2022-07-21 14:30
Yeah it's odd, it worked on chrome too

**Comment by rixx** [comment] 2022-07-21 19:40
Do the console errors (in the last second of your video) only show up once you try to download the export, or are they present from the first page load?

I just tested this site with an iPad Safari (the only I have access to), and it worked as intended: showed a pop-up asking if I'd like to download or view the csv file.

Next we'll have to try to reproduce the problem on the desktop version of Safari, I suppose.

**Comment by rixx** [comment] 2022-09-09 21:08
Closing due to lack of information. Feel free to re-open with more details.

**Closed by rixx** 2022-09-09 21:08 UTC
