### ISSUE TITLE
Add hint on how to open reviews

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#1013] opened 2020-09-26 21:45 UTC
## Current Behavior

I populated a fresh checkout with the cfp stage (`python manage.py create_test_event --stage cfp`) and I wanted to look into the reviews. The review page at http://localhost:8000/orga/event/democon/reviews/ has a note at the top saying "Reviews are currently closed."

I wondered how to open them.

## Expected Behavior

I expect the note to provide information on how to open the reviews. My problem was that I haven't had a team that would be marked as reviewers.

## Steps to Reproduce

1. Init a Pretalx instance
2. `python manage.py create_test_event --stage cfp`
3. Go to reviews at http://localhost:8000/orga/event/democon/reviews/

## Context

I wanted to try things out, so I wasn't really following a usual flow. So this might be a non-issue if you follow a regular configuration flow.

I just thought I bring it up as usage experience when you're fresh to the system are hard to get when you're used to a system.

I'd be happy to create a PR if this should be improved. I'm also happy to put more thought into this if needed.

## Your Environment

* Version used: HEAD
* Environment name and version (e.g. Chrome 39, python 3.5): Firefox, Python 3.8
* Operating System and version (desktop or mobile): Debian, Desktop.

**Comment by rixx** [comment] 2021-09-23 15:15
I couldn't reproduce this issue – let's hope it was fixed in the past year.

**Closed by rixx** 2021-09-23 15:15 UTC

**Comment by BjornW** [comment] 2024-02-15 10:53
I can see this issue. There is a message warning about reviews being closed but no indication on how to resolve this. We are using a self-hosted install.

**Comment by rixx** [comment] 2024-02-15 11:00
Reviews being closed can have a variety of causes, and not all users can change this fact. Adding instructions would be very fragile and in many cases not helpful.

Reviews being closed can refer to the current review phase not permitting reviews, or there not even being an active review phase, or the user in question not being a reviewer, or not having review permissions for the particular proposal in question, if a particular proposal is opened. This is up to the event organisers to handle.

**Comment by BjornW** [comment] 2024-02-15 11:25
Is it possible to determine the role of the current user? This could be helpful to show the correct message. In our case it was the admin role. We are still learning Pretalx, so perhaps using this info could help determine the correct message as well. The installation was rather new. Just thinking out loud to see if there are ways to make the interface more user-friendly :)

**Comment by rixx** [comment] 2024-02-15 12:21
Happy to merge pull requests to that extent, but won't be able to prioritise this request atm.
