### ISSUE TITLE
a list edition mode in the output mail box

### ISSUE THREAD

**Issue by vincent-lucy** [pretalx/pretalx#1583] opened 2023-09-16 15:39 UTC
### Problem and impact

if you have for example 70 mails (that are generated in the composition page) in the mails/sent page, if you want to suppress 3 item on the third page, you can not do a mass edition/suppression and you are redirected to the first page after suppressing your first item.

a list selection for suppression would be very handy

**Comment by rixx** [comment] 2023-09-16 17:53
Yes, bulk changes in list views would be great to have. Contributions are welcome! Closing as duplicate of #1330

**Closed by rixx** 2023-09-16 17:53 UTC
Labels: type: feature
