### ISSUE TITLE
schedule.json truncated temporarily

### ISSUE THREAD

**Issue by xfxf** [pretalx/pretalx#1535] opened 2023-07-26 02:22 UTC
### Problem and impact

When trying to import JSON for a conference (from https://pretalx.com/pyconau-2023/schedule/export/schedule.json) for a new published schedule version - I was receiving truncated data, confirmed from multiple geographically seperated machines.

This appeared to 'fix' itself after about 20 minutes.

I can't provide much more information given I cannot easily reproduce, but I notice recent commits have changed caching behaviour for this URL, so wanted to raise a bug.

**Comment by xfxf** [comment] 2023-07-26 04:44
Turns out I still had the truncuated version open in a browser.  130454 bytes long (non-truncated schedule appears to be approximately double this).
Screenshot: 
![image](https://github.com/pretalx/pretalx/assets/138684/af699f19-0840-4290-ae55-b4d099f6a27a)

**Comment by rixx** [comment] 2023-07-28 00:18
Cannot reproduce; might be due to the temporary caching measures that have been rolled back – but that change was reverted five days ago. Closed as non-reproducible.

**Closed by rixx** 2023-07-28 00:18 UTC
Labels: type: bug
