### ISSUE TITLE
Feature Request: Show details of modifications in a Submission's History

### ISSUE THREAD

**Issue by bauglir** [pretalx/pretalx#921] opened 2020-05-08 12:11 UTC
## Problem you are facing

The 'History' sidebar on a Submission's page shows when a Submission was modified but doesn't appear to show the specifics of that modification. This can raise questions when, for instance, an organizer makes modifications to a Submission the submitter is unaware of.

## Possible Solution

Log additional data with the `pretalx.submission.update` logging action, detailing the type of modification. This additional data could be shown in a collapsible section of a history entry, or upon hover.

What additional data should actually be logged is likely what makes this a non-trivial thing to implement, as there is a myriad of options. Should just the type of modification be logged, should the old values be logged, how should attachments be handled?

Logging the modified attributes would probably be an easy start at least giving some insight, but I guess this can also quickly spin out of control. Perhaps a Python alternative to Ruby's [paper_trail](https://github.com/paper-trail-gem/paper_trail) can be of use here?

## Context

The specific case that made me aware of this was a submission to a conference where the type of Submission was altered without my knowledge. When the Submission got accepted, the altered type puzzled me and needed some additional input from an organizational member.

**Comment by rixx** [comment] 2020-05-08 19:15
You're absolutely right that we should do this. Even though your issue description is very clear and thorough, I'll close this issue as a duplicate of #400. Linking the two so that your comments will be useful when tackling the issue – thanks for bringing it up!

**Closed by rixx** 2020-05-08 19:15 UTC

**Comment by bauglir** [comment] 2020-05-11 07:38
Thanks for the feedback. I had checked if there was already a duplicate, but I clearly missed it :)
