### ISSUE TITLE
Allow 'external' organized talks (Speaker != submitter)

### ISSUE THREAD

**Issue by s-light** [pretalx/pretalx#614] opened 2019-03-05 11:25 UTC
## Problem you are facing / Context
On our last event we had a bunch of talks from on of our sponsors that were organized by on `contact person` of them.
But the Talks were held by different speakers.
this is not really handled by the current 'Speaker identified by email' concept.

## Possible Solution
initially the `contact person` added submissions with the actual speaker in the title..
later i changed this:
removed the speaker from the title and added the speaker with a 'placeholder' mail-address.
then removed the original speaker (the `contact person`) from the speaker-list.
this way the `contact person` can not update or change the content of the submission anymore - but the schedule shows the correct speaker names...

#12 → seems something similar was implemented but not working ?
also this request could be a duplication of #527 ?
iam not sure right now.. so i will submit this one..

**Comment by rixx** [comment] 2019-03-10 23:04
I'm pretty sure this is a duplicate of #527, yes.

**Closed by rixx** 2019-03-10 23:04 UTC
