### ISSUE TITLE
The link for downloading ical etc. from schedule does not appear

### ISSUE THREAD

**Issue by ericsfraga** [pretalx/pretalx#1140] opened 2021-07-20 10:52 UTC
## Current Behavior
When visiting the schedule (for the JuliaCon 2021 conference specifically), there is meant to be a little drop-down menu from a button that looks like </>. This button does not appear for me. I am using Debian testing (up to date last week) and Firefox from that distribution. I do not block JavaScript and the only add-ons I have are https everywhere and facebook container.

## Expected Behavior
I would expect to see the drop down menu button.

## Steps to Reproduce

1. Start firefox
2. Visit https://pretalx.com/juliacon2021/schedule/
3. Button next to "Version 0.2" is not there

Interestingly, if I use eww, the Emacs web browser, the links that would be in the drop down menu appear (although the button does not).
## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5): Firefox 78.11
* Operating System and version (desktop or mobile): Debian 11.0
* Link to your instance, if in production: https://pretalx.com/juliacon2021/schedule/

**Comment by rixx** [comment] 2021-07-20 12:17
Thank you for this report. I can't tell why this would happen – the button is rendered unconditionally and I don't think that it uses some modern CSS to show up. That said, Firefox 78 is fairly old, so it *could* be due to that.

I can't currently reproduce the issue at all, I'm sorry to say. I'll be happy to merge a fix, of course, if somebody finds one!

**Comment by ericsfraga** [comment] 2021-07-20 12:24
Okay, no worries. Yes, I realise that v78 may be old but it's the stable release that Debian comes with. Thank you.

**Comment by giordano** [comment] 2021-07-21 15:31
I don't know if this is related, but I don't see the `</>` link in Chrome 91 on Android, it isn't even when scrolling to the right (the schedule table is quite large) 

![Screenshot_20210721_162738](https://user-images.githubusercontent.com/765740/126515917-76de99f2-0536-408c-a984-f03b46bc0280.jpg)

**Comment by rixx** [comment] 2021-07-21 17:39
Yes, the exports aren't meant to be visible on mobile browsers, as the interface is already close to cluttered, and the export links aren't typically useful there.

**Comment by rixx** [comment] 2021-08-04 15:55
Closing for now, happy to re-open if this pops up again.

**Closed by rixx** 2021-08-04 15:55 UTC
Labels: good first issue, help wanted, issue:bug 🐛

**Comment by confluence** [comment] 2021-10-08 06:54
OK, I understand that, but this is happening in *desktop* browsers (as in the original report, but reproduced in new versions). There's a simple workaround (at least under the conditions that I have observed), so a fix is not urgent, but I'm commenting in the hopes that the issue will be reopened.
