### ISSUE TITLE
/submissions API response does not contain slot although submission is confirmed and a slot assigned

### ISSUE THREAD

**Issue by Nakaner** [pretalx/pretalx#548] opened 2018-12-06 22:52 UTC
## Expected Behavior

`https://pretalx.com/api/events/fossgis2019/submissions` should return a slot for event if I have all permissions.

## Current Behavior

However `slot` is `null` although I confirmed the talk (it's my own talk) and a slot is assigned.

## Steps to Reproduce

There is no released/public schedule yet, only the WIP version.

1. Set status of the talk to accepted.
2. Assign a slot.
3. Send acceptance email.
4. Confirm the talk (click on confirmation link).
5. API query.

## Context

You can try this with submission V3PC3M.

EDIT: I need this feature for FOSSGIS 2019 in order to be able to send emails with the date and time of the talk to the speakers **before** I publish the schedule.

This bug could be fixed by making the whole WIP schedule accessible via the API.

## Your Environment

FOSSGIS 2019, pretalx.com

**Comment by rixx** [comment] 2018-12-07 01:15
I'm afraid this is not a bug, and a wontfix: The slot element in the submision API refers to a published slot. We might make this clearer in the API.

> EDIT: I need this feature for FOSSGIS 2019 in order to be able to send emails with the date and time of the talk to the speakers before I publish the schedule.

The usual way to do this is to release a schedule, but to uncheck "Show schedule publicly" for the time being – is there a reason why this will not work for you?

> This bug could be fixed by making the whole WIP schedule accessible via the API.

We do this in https://pretalx.com/api/events/fossgis2019/schedules/wip/

**Closed by rixx** 2018-12-07 01:15 UTC
