### ISSUE TITLE
Non-ascii characters with accent not found

### ISSUE THREAD

**Issue by Rufus125** [pretalx/pretalx#1683] opened 2024-02-12 21:01 UTC
### Problem and impact

We have a speaker named "André". When searching for "Andre" in 
https://pretalx.linuxtage.at/orga/event/<eventslug>/submissions/ I was not able to find him.

postgres=# \l
                                             List of databases
   Name    |  Owner   | Encoding | Collate |  Ctype  | ICU Locale | Locale Provider |   Access privileges   
-----------+----------+----------+---------+---------+------------+-----------------+-----------------------
 pretalxdb | pretalx  | UTF8     | C.UTF-8 | C.UTF-8 |            | libc            | 

Is it possible to set or migrate to a collation so that it is possible to have a  accent-insensitive comparison?

### Steps to reproduce

1.
2.
3.
4.

**Comment by rixx** [comment] 2024-02-13 09:55
Duplicate of #1555. I'll quote from my longer answer there:

> I'd also prefer to have accent insensitive search, but maintaining two janky solutions, plus docs support for the less janky one (on the Django side, at least) sounds like a huge hassle. If anybody wants to step in and contribute, including tests, I'd be willing to talk about it, but until then, I'll close this as "not planned" (pending better Django support or outside contributions).

**Closed by rixx** 2024-02-13 09:55 UTC
Labels: type: bug
