### ISSUE TITLE
Compose Email selected is "OR" should be "AND"

### ISSUE THREAD

**Issue by jberkus** [pretalx/pretalx#887] opened 2020-02-21 21:35 UTC
## Current Behavior

It appears that the different criteria in the Compose Email recipient selector are "ORed" together, instead of being "ANDed" as a cumulative filter.  This means that if, for example, I want to send a email to all accepted speakers in a specific track, I cannot do it; I can send an email to all accepted speakers, or all speakers in a track whether they were accepted or not.

It's also possible that the criteria are overrides, and rather than being ORed, it's simply that the second critieron is used, and the first one is ignored.

## Expected Behavior

Selector filters should be ANDed together, so if I select "All Accepted Speakers" and "Type: Lightning Talk", I get only Lightning Talk speakers who have been accepted.

## Steps to Reproduce

1. Have an event with more than one Type and a mix of accepted, rejected, and undetermined speakers, in both types.
2. Go to compose email interface.
3. Select "Everyone with submission(s) that have not been accepted/rejected yet"
4. Select one of the two Types
5. Select Send Email
6. You will get emails both to all of the speakers of that Type, regardless of the status of their talks (it also may be all speakers of that Type AND all speakers of that status, not sure).

## Context

I think the above explains the context.  I worked around the problem via hand selection.

## Your Environment

Pretalx hosted

**Comment by rixx** [comment] 2020-02-21 22:27
This is a duplicate of #715, which we'll hope to address soon this year.

**Closed by rixx** 2020-02-21 22:27 UTC
