### ISSUE TITLE
Markdown output from preview to live differs

### ISSUE THREAD

**Issue by pkornherr** [pretalx/pretalx#1721] opened 2024-03-28 21:13 UTC
### Problem and impact

While using pretalx for eh21, I noticed that the speaker preview renders markdown differently than the live view. For example
```text
~~strikethrough~~
```
renders as strikethrough as wanted in the preview, but shows
```
~~strikethrough~~
```
in the talk view.

### Expected behaviour

Expected is that the preview renders the same as the live view.
I don't ask for a specific feature, but it should behave the same way.

### Steps to reproduce

1. Enter pretalx speaker view
2. Create a text containing markdown with 
```
~~foo~~
```
content
3. Preview the talk. "foo" is strikethroughed.
4. View the talk on the live view
5. You'll see
```
~~foo~~
```
, the markdown code doesn't get rendered the same way as in the preview

### Screenshots

![Bildschirmfoto vom 2024-03-28 22-11-07](https://github.com/pretalx/pretalx/assets/125471898/b42ff34a-619d-4c81-83d6-27ad61e0ee6b)
![Bildschirmfoto vom 2024-03-28 22-11-16](https://github.com/pretalx/pretalx/assets/125471898/39968f8d-059d-4023-be2e-868dc96f6195)
![Bildschirmfoto vom 2024-03-28 22-11-44](https://github.com/pretalx/pretalx/assets/125471898/bb19a6ad-aa5a-4e5f-bff7-07d220d89c8e)

### Browser (software, desktop or mobile?) and version

Firefox on Linux

### Operating system, dependency versions

Ubuntu mantic

**Comment by rixx** [comment] 2024-04-02 12:13
Duplicate of #1574

**Closed by rixx** 2024-04-02 12:13 UTC
Labels: type: bug
