### ISSUE TITLE
markdown image link in Text section is not working

### ISSUE THREAD

**Issue by ChAoSUnItY** [pretalx/pretalx#1539] opened 2023-07-27 06:25 UTC
### Problem and impact

When I trying to embed a gif into Text section, it would become an invalid html tag that renders tag itself instead of the gif.

### Expected behaviour

The gif should be rendered.

### Steps to reproduce

1. Add `![image](https://ocf.tw/p/oscvpass/2019/animation.gif)` in Text section
2. Save the changes
3. Go to CfP
4. You can see the image link is rendered as `<img alt="image" src="https://ocf.tw/p/oscvpass/2019/animation.gif">` instead of the gif itself.

### Screenshots

Gif image link in Text section:
![image](https://github.com/pretalx/pretalx/assets/43753315/5375c3aa-aebd-480b-808e-7e7357ac193d)

Acutal CfP Text section:
![image](https://github.com/pretalx/pretalx/assets/43753315/bc335559-51a5-4d31-9a77-ccd0defe1750)

### Version

2.3.2

**Comment by rixx** [comment] 2023-07-28 00:32
This is not a bug: pretalx does not currently support images in text sections. Images are purposefully not listed in our [Markdown guide](https://docs.pretalx.org/user/markdown.html).

Supporting images in Markdown would require:

- parsing all textboxes that support Markdown on all writes (alt: before all writes)
- find non-local image links
- retrieve the remote image
- reject the edit (alt: the request) if the retrieval is not possible, or yields a non-image file, or an image file that is too large
- save and host the linked image file
- rewrite the Markdown content with the new local URL
- proceed to save

I'd be happy to review a PR covering these steps (either version works, though I'd probably prefer the client-side blocking one), but am closing this issue in the meantime, as a) this is currently intended behaviour, not a bug, and b) I cannot prioritise this feature right now, unless it's via PR review or a commission.

**Closed by rixx** 2023-07-28 00:32 UTC
Labels: type: bug
